# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:0JZhAtkhxCw70RO9wj9nGIfyP/x+mip4NYXLn8J1caJZfXmwfbTjog==,iv:9BKpPL413/bSdqggLoN+WyuEA1VqHH3RjMY10P7jeUM=,tag:arzn0S1Oxb5kbCYp1Ui2Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-22T03:35:31Z"
    mac: ENC[AES256_GCM,data:E2nPiFDCzui04BtT8k5AnSMH4MVhZEfjhGHbPop6PDpkcKLnOPDYcAkE+vdsJXIHJKIap/58+TaTxSGUKS2Gt4kv6CUdX/WrGeFJmE1INyPibBpZQGBnlWqwJW3iGFbsATGErrG8YHozOGsYT/TVvG89ARAmpnvkGikzKYJCVMs=,iv:U+zl/ZC4UwDaPQNWC/OpyV4WcqvqNtnpB/Bnh419pOI=,tag:mfpCy7u58h6YLTAKB6+/Dg==,type:str]
    pgp:
        - created_at: "2021-04-22T03:35:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4mc6yuVUWZUAQ//XlgEr2ngpUeyrQBBhU9lggIsqa7+5mkiZ4hzG0OAVeH8
            46ku1+w834an9S07mQiNBP/InENnNwLfYO+ELp3vuVB2PixQEIytlz0i7wQ/8gGa
            pKXCkEW/6kOCGwVTZsM0sS68eKTTjlXKmEOSJKZ1rRsT63ngFL04+3gZO3T6AwW8
            asX/OuFJRQjLcrMCDT3WHkeYIT7F+8uwGpCMcM9FMPK+IiyXqikMYD0Fqj4AW8ar
            wzUCZMrh5wi5R26H9RpiFQ/UqH/S5nQ4iVmlD6By2R0doSu9frTN1bfzSDTYMaSb
            D+nqIfAOsso/fheiT9TRTI5AworPdzp4+he3yZ9q7tsR6XMqQaVv7/SGQQJf3y/q
            6QvP8jlIqR+DeceMzHwDiZkehcYkvCLXWS8i9FsFAVi/gizyC0fb2cHNyDIcPL5C
            hpPSll3xiz6w3EdF6grgRjZ07MxwdqlMihTeW7X1BU1pQz8vG83nNhK31lmWvapv
            SM4LOOEK1RnXG2U0hPno7joAHP+kmRc5b3UA/jESdaynpjo1onI6fKBzYNfMfOnx
            2PGA9MKOIZRjPWCv62LSrAHPKDF4bea6d83AMth8JUOiPTjJRjtcbSpYB6r42U5P
            IkvxjE0CxV/Qd1yOm8WjVRdTM6+C6a5P2FarmFGvY0ImLwjTyZ8JNZjJrauzIW3S
            XAH8h8uMsI3zlF0O17YHglyWDKZNTN0xCTiA0ejE7bG2TEJ0hRuw4wjWxfytDqxQ
            q7cr7tZNzwq/xGLOIx6TNHFIivMbaJ7yO53U6hHwCkl5rXdPUH5lXvmuum2G
            =qZTf
            -----END PGP MESSAGE-----
          fp: 45C76A28DB939AD4F326D1675D93DE98125D4A39
        - created_at: "2021-04-22T03:35:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6u1pca+4BxHAQ/6Ag87E+dYePM8gcsEM5cgXyFQ1M2lW++fk9FKPOpuNQWs
            ODEhCA48RHpcb46pkSG5dzNtfuqzN8c4R1rSeA8lKiKv6EgIJbUUmZfqNliq6LlZ
            eXAnNlNeiV087pYqmFG2RXqGUOMJ0VaxQ47HqSZbSBewjQ9nw5ZsFoT+w7BHoMXM
            qtUrwzu8NGz1WxcqS41vlf64Dew6sP2edj3TK+jAemITOFPDfFZoCze91yOgMviu
            RiGLGE75hXh/rug1KxZDx2zfDhVbWjxdYkcZUEOtiysMA7+GrOwp68vZ5g1MWTKa
            1OYSjpsxPL3n6W1lGLLDLBm5NJZ6v7CnOe1pERy5vVZi37kbwjLNL0IgM2pKvPz5
            JOGk9i1oqfJ6f0yA+1gMAIOzoJV7g/G6z82wRV18HdmNmxDv3CF/ghU3pbtF7mgH
            n47jOs/zWOL23A3Vr8ap180XHgDn4lYuGabQePUCbD+mmkjl5Qo5RkltBLVM+A94
            QkL4/jIG9piWKhQzC7LK7dYA/q3nGOI9JK93KSaWyeE3NZKzPzb/buPNlXnCmyK0
            a5Bxl7g/u5CMtUoPQR5OR3aUu1ZdOjDUEUEFVvrDam5410jjNzof/bYDUt3TzNtr
            vYgwfogl1qwDnN++M/3N93aWQ0bXKDzcQ1WzX+iwTWWXp6A13CZfCGnOwgcGQVrS
            XAG3VRi0uhRziRFjbEfWUT1rI0Nc+GCjJsBzEU5vr/ZkM4yNWBAfZn8u7pz7dLki
            2W1dAh9BfKjMnkhPj+ZNmhID33kQ6Ppu6vsAwBMipiG+qcAn9y/iWizIE8j4
            =0T/M
            -----END PGP MESSAGE-----
          fp: 8708ED22223EA371FF5C8521D7BE2CC9BCED75E7
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
